# Site settings
title: Meet Sanchit!
description: Sanchit Balchandani - @inovizz
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sanchit Balchandani
user_description:
  <p>Result-oriented Software Developer with over 15 years of extensive experience in application development, including 2+ years specializing in cutting-edge Generative AI applications. Demonstrated expertise in Python, Node.js, object-oriented programming, microservices architecture, and RESTful backend development using modern frameworks such as FastAPI, Django, Flask, and Django REST Framework.</p>
  <p>Currently working at EPAM India (since 2019) as an Engineering Manager, leading the Python Discipline and managing a dynamic team of 260+ professionals. From a technology perspective, I serve as a GenAI Architect, designing and delivering end-to-end AI-driven solutions across multiple business streams, focusing on intelligent automation and enterprise-scale AI adoption.</p>
  <p>Proficient in DevOps technologies, including Docker (containerization), Kubernetes (orchestration), AWS Cloud (scalable infrastructure), Jenkins (CI/CD), and Terraform (Infrastructure as Code), enabling efficient and resilient software delivery pipelines.</p>
  <p>Beyond work, I am an active community leader and core member of the Hyderabad Python User Group since 2016, contributing to the growth of the Python ecosystem in India. I’ve also held leadership roles such as Chair, PyCon India 2023 and PyCon Hyderabad 2022, and Co-organizer for PyCon India 2021 & 2018, successfully organizing large-scale developer conferences that foster knowledge sharing and collaboration.</p>
user_title: Engineering Manager @ EPAM India
email: sanchit@inovizz.com
twitter_username: inovizz
github_username: inovizz
linkedin_username: inovizz

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
